name: Main CI Workflow
on:
  push:
    branches:
      - master       # Push events on master branch
      - 'releases/*'   # Push events to branches matching refs/heads/releases/*
      - '!refs/pull/*' # Push events on branches that do not match refs/pull/*
  pull_request:
    branches:
      - master       # Push events on master branch
jobs:
  Ubuntu:
    name: Run Android on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        version: 10.x

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: npm install
      env:
        APPCENTER_BRANCH: master
        APP_SECRET_PASSPHRASE: ${{ secrets.APP_SECRET_PASSPHRASE }}

      run: |
        echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        yarn install

    # - name: Test
    #   run: yarn test

    # - name: Lint
    #   run: npm run lint

    # - name: Format
    #   run: npm run format
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Fastlane Setup
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Fastlane Build
      env:
        APPCENTER_BRANCH: master
        APP_SECRET_PASSPHRASE: ${{ secrets.APP_SECRET_PASSPHRASE }}
      run: |
        yarn run fast:build

  # macOS:
  #   name: Run macOS
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master

  #     - name: Set Node.js 10.x
  #       uses: actions/setup-node@master
  #       with:
  #         version: 10.x

  #     - name: npm install
  #       run: npm install

  #     - name: Bootstrap
  #       run: npm run bootstrap

  #     - name: Compile
  #       run: npm run build

  #     - name: npm test
  #       run: npm test
  # Windows:
  #   name: Run Windows
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@master

  #   - name: Set Node.js 10.x
  #     uses: actions/setup-node@master
  #     with:
  #       version: 10.x

  #   - name: npm install
  #     run: npm install

  #   - name: Bootstrap
  #     run: npm run bootstrap

  #   - name: Compile
  #     run: npm run build

  #   # TODO: This currently ignores exec due to issues with Node and spawning on Windows, which I think is exacerbated by Jest.
  #   # It doesn't seem to affect behavior in actions themselves, just when testing with Jest.
  #   # See other similar issues here: https://github.com/nodejs/node/issues/25484
  #   - name: npm test
  #     run: npm run test-ci
